config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'weather#show'
  get 'weather_forecast', to: 'weather#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

  def show
    begin
      if params[:zip_code].present?
        zip_code = params[:zip_code]
        #check cache value
        cache_key = "weather_forecast_#{zip_code}"
        @from_cache = @forecast = Rails.cache.read(cache_key)
          
        unless @forecast
          #fetch forecast for zipcode
          @forecast = fetch_forecast(zip_code)
          Rails.cache.write(cache_key, @forecast, expires_in: 30.minutes)
        end
      end
      render :show, status: :ok
    rescue => e
       @errors = e
    end
    
  end

  private

  def fetch_forecast(zip_code)
    #Api call to fetch weather forecast
    response = Services::Api.new.get_weather_forecast(zip_code)
    forecast = response.parsed_response["forecast"]["forecastday"].first["day"]
    {
      current_temperature: forecast["avgtemp_c"],
      high_temperature: forecast["maxtemp_c"],
      low_temperature: forecast["mintemp_c"]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Forecast" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/_search.html.erb
<%= form_with url: weather_forecast_path, method: :get do %>
  <div class="field">
    <%= label_tag :zip_code, "Enter zipcode:" %>
    <%= text_field_tag :zip_code, params[:zip_code] %>
  </div>
  <%= submit_tag "Get Forecast" %>
<% end %>

app/views/weather/show.html.erb
<h1> Weather Forecast </h1>
<%= render :partial => 'search' %>

<% unless @errors.nil? %>
  <p1><%= @errors.message %></p1>
<% end %>

<% if @forecast %>
  <div class="forecast">
    <h2>Forecast: </h2>
    <p>Current Temperature: <%= @forecast[:current_temperature] %>°C</p>
    <p>High: <%= @forecast[:high_temperature] %>°C</p>
    <p>Low: <%= @forecast[:low_temperature] %>°C</p>
    <% if @from_cache %>
      <p style="color:red"><em>Result pulled from cache</em></p>
    <% end %>
  </div>
<% end %>